version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: charles
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
    networks:
      - hacksmith
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: charles
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
    networks:
      - hacksmith
networks:
  hacksmith: